export default {
  // 姓名
  NAME: 'studentName',
  // 手机号
  TELPHONE: 'phone',
  // 报名项目
  SIGN_PROJECT_ID: 'projectId',
  SIGN_PROJECT_NAME: 'projectName',
  // 套餐
  PACKAGE_ID: 'projectPackageId',
  PACKAGE_NAME: 'projectPackageName',
  // 复学时间
  TIME_OF_RETURN_TO_SCHOOL: 'returnDateList',
  // 支付金额
  PAYMENT_AMOUNT: 'payPrice',
  // 退款金额
  REFUND_AMOUNT: 'reducePriceList',
  // 退款原因
  REASONFOR_RETURN: 'reduceReasonList',
  // 结课类型
  COURSE_TYPE: 'endClassType',
  // 服务起始时间
  SERVICE_STARTTIME: 'startTime',
  // 服务结束时间
  SERVICE_ENDTIME: 'endTime',
  // 顾问
  CONSULTANT: 'saleName',
  // 班导
  CLASS_GUIDE: 'tutorName',
  // 最新跟进时间
  LATEST_FOLLOWUP_TIME: 'modifyTime',
  // 学校
  SCHOOL: 'school',
  // 专业
  PROFESSION: 'professional',
  // 目标行业
  TARGET_INDUSTRY: 'industry',
  // 目标公司
  TARGET_COMPANY: 'company',
  // 目标岗位
  TARGET_POSITION: 'post',
  // 目标工作地点
  TARGET_WORK_LOCATION: 'workCity',
  // 当月选课
  SELECTED_CLASS_INTHEMONTH: 'selectedCourseInTheMonthList',
  // 当月课程
  CURRENT_MONTH_COURSE: 'theCourseInTheMonth',
  // 1v1消课
  ONEVSONE_CLASS_ELIMINATION: 'oneVsOneClosed',
  // 小班课消课
  LITTER_CLASSCOURSE: 'smallClassClosed',
};
